version: '2'

services:
  postgres:
    build: .
    image: shintech/database
    container_name: postgres
    networks:
      default:
        ipv4_address: 192.168.0.8
networks:
  default:
    external:
      name: shintech  